In [111]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
import sklearn.metrics

In [97]:
images_filename = 'queries/image_queries.txt'
images = pd.read_csv(images_filename, delimiter = "\t", header=None)[0].tolist()
filter(None, images)
print(len(images))
images[:10]

17994


['холодовая крапивница',
 '{searchTerms}',
 'гематокритная трубка',
 'карта россии с реками и морями',
 'иван дорн фото семья',
 'дворяне 17в',
 'винтажные картинки бабочки  для декупажа',
 'черчиль',
 'scott russell sanders essay',
 'Suspender Nylon site: .us .php sid']

In [106]:
web_filename = 'queries/web_queries.txt'
notimages = pd.read_csv(web_filename, delimiter = "\t", header=None)[0].tolist()
filter(np.isnan, notimages)

del notimages[606]
print(len(notimages))

notimages[:10]

99711


['ажурные узоры спицами',
 'Duyerli',
 'гост17608 91',
 'гдз по математике 6 класс виленкин',
 'детская общественная организация',
 'oscillator de onda triangular con 741',
 'фильмы 2016',
 'россия швеция онлайн трансляция',
 'домашние животные картинки',
 'придумайте японское хокку о горе']

In [108]:
# dataset = {}
# dataset['X'] = list(images.copy())
# dataset['X'].extend(list(notimages))
# dataset['y'] = [1]*len(images)
# dataset['y'].extend([0]*len(notimages))

# df = pd.DataFrame(dataset, index=None)
X = []
X = images.copy()
X.extend(notimages)
y = [1]*len(images)
y.extend([0]*len(notimages))

len(images), len(notimages), len(X)

(17994, 99711, 117705)

In [112]:
count_vect = CountVectorizer()
for i, rec in enumerate(X):
    if rec is np.nan:
        print(i, rec)
print(len(X))
X_counts = count_vect.fit_transform(X)
X_counts.shape

117705


(117705, 77117)

In [114]:
tfidf_transformer = TfidfTransformer()
X_tfidf = tfidf_transformer.fit_transform(X_counts)
X_tfidf.shape

(117705, 77117)

In [115]:
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=0.2, random_state=1)

In [116]:
clas = LogisticRegression()

In [117]:
clas.fit(X_train, y_train)

/Users/irina/.pyenv/versions/3.7.0/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [122]:
clas.score(X_train, y_train)

0.8556454696062189

In [123]:
clas.score(X_test, y_test)

0.8359882757741812

In [126]:
queries = ['сайт знакомств', 'генеалогическое древо']
q_counts = count_vect.transform(queries)
q_tfidf = tfidf_transformer.transform(q_counts)
q_tfidf.shape

(2, 77117)


(2, 77117)

In [127]:
clas.predict_proba(q_tfidf)

array([[0.97445163, 0.02554837],
       [0.71956578, 0.28043422]])

In [130]:
# самый некартиночный из картиночных
q_counts = count_vect.transform(images)
q_tfidf = tfidf_transformer.transform(q_counts)
q_tfidf.shape
images_probs = clas.predict_proba(q_tfidf)
print(images_probs)
max_ind = 0
for i, arr in enumerate(images_probs):
    if arr[0] > images_probs[max_ind][0]:
        max_ind = i
print(images[max_ind])

[[0.75209527 0.24790473]
 [0.68784733 0.31215267]
 [0.78184827 0.21815173]
 ...
 [0.77120723 0.22879277]
 [0.48136952 0.51863048]
 [0.50215312 0.49784688]]
шоу голос 4 сезон смотреть онлайн в хорошем качестве 1 канал


In [132]:
# самый картиночный из некартиночных
q_counts = count_vect.transform(notimages)
q_tfidf = tfidf_transformer.transform(q_counts)
q_tfidf.shape
images_probs = clas.predict_proba(q_tfidf)
print(images_probs)
max_ind = 0
for i, arr in enumerate(images_probs):
    if arr[1] > images_probs[max_ind][1]:
        max_ind = i
print(notimages[max_ind])

[[0.49431327 0.50568673]
 [0.86738072 0.13261928]
 [0.85975281 0.14024719]
 ...
 [0.96662372 0.03337628]
 [0.93891364 0.06108636]
 [0.9572518  0.0427482 ]]
фото
